### ISSUE TITLE
vertx 4.2.1

### ISSUE THREAD

**Issue by ksclarke** [vertx-howtos/graal-native-image-howto#10]
Like the 4.0.2 ticket, there is a new version of vertx 4.1.x that it would be nice to see this working with. It includes a new netty, but I'm also not making much headway in trying to get the native-image.properties config working.

_Edit:_ Updated title to 4.2.1

**Comment by ksclarke** [comment]
Also using graalvm 21

**Comment by pmlopes** [comment]
At the moment I personally don't have the capacity to investigate the needed configuration. Any community contributions are welcome!

**Comment by ksclarke** [comment]
I made a little headway but got stuck at https://github.com/netty/netty/issues/11369 (which I see you opened with Netty).

**Comment by ksclarke** [comment]
Since PR #12 solved some outstanding issues for me, I've submitted a PR (#13) that will update this project's step-2 POM. I've confirmed it working with GraalVM 21.3.0, Vert.x 4.2.1 and 0.9.8 of the new GraalVM native-image Maven plugin.

Requests for changes to what I've submitted are welcome.

**Comment by ksclarke** [comment]
Closing now, since I neglected to close this when the PR linked above was merged. I'll probably circle back around again an update to the latest Vert.x again in the near future, but the howto is now using 4.2.3 (later than the 4.2.1 mentioned in this ticket).
