### ISSUE TITLE
More Up To Date Example

### ISSUE THREAD

**Issue by sstubbs** [vertx-howtos/graal-native-image-howto#2]
Hi,

Firstly thank you for this. It is a very exciting prospect running vertx with less heap size and quicker start time. Would there be anyway to update this now that netty 4.1.36 includes your pull request? It would be really great to be able to use this. I understand though it might be better to wait for 4.1.36 to actually be included in vertx itself.

**Comment by pmlopes** [comment]
I'd rather wait for netty upgrade in vertx core and then update this example. What will happen then is that no substitution code will be needed and less config too. You can try to force the netty version to be 4.1.37 (the release after changed the substitution files for the stable graal release).

**Comment by sstubbs** [comment]
OK great thanks for the information. I will wait too. I tried the example with a few of my smaller vertx projects with no success. Really looking forward to this.

**Comment by pmlopes** [comment]
In the meantime you can see this branch of the examples with a few projects and their config. I try to keep it up to date with the latest releases

https://github.com/vert-x3/vertx-examples/tree/native-examples/native-image-examples

**Comment by sstubbs** [comment]
Oh brilliant thank you.

**Comment by sstubbs** [comment]
I've been trying these example with the following dockerfile

```
FROM oracle/graalvm-ce:1.0.0-rc16

RUN yum install -y wget
RUN wget http://www.eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
RUN tar xzf apache-maven-3.3.9-bin.tar.gz
RUN mkdir /usr/local/maven
RUN mv apache-maven-3.3.9/ /usr/local/maven/
RUN alternatives --install /usr/bin/mvn mvn /usr/local/maven/apache-maven-3.3.9/bin/mvn 1
```

I first tried 19.0.0 which fails during buld. 1.0.0-rc16 does build but then when I try and run it with

`./vertx-native-image-http-server-example run vertx.HTTPVerticle`

I get the following error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate io.vertx.core.impl.launcher.commands.StartCommand
        at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:34)
        at io.vertx.core.spi.launcher.DefaultCommandFactory.create(DefaultCommandFactory.java:44)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.getNewCommandInstance(VertxCommandLauncher.java:158)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:213)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:361)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:324)
        at io.vertx.core.Launcher.main(Launcher.java:45)
Caused by: java.lang.InstantiationException: Type `io.vertx.core.impl.launcher.commands.StartCommand` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
        at java.lang.Class.newInstance(DynamicHub.java:740)
        at io.vertx.core.cli.impl.ReflectionUtils.newInstance(ReflectionUtils.java:32)
```

**Comment by sstubbs** [comment]
I think I will just wait for it to be supported by vertx itself. Was just a nice to have feature.

**Comment by pmlopes** [comment]
@sstubbs please see the examples link above. Those are more up to date as I'm waiting for the upgrade to netty 4.1.37 so we don't need substitutions and most of the configuration from this how-to.

**Comment by sstubbs** [comment]
OK I was talking about those examples in the link. Perhaps I am doing something wrong. I will try again.

**Comment by sstubbs** [comment]
OK they are working now. This dockerfile works. 

```
FROM oracle/graalvm-ce:19.0.0

ENV MAVEN_OPTS -Xmx30g

RUN yum install -y wget
RUN wget http://www.eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
RUN tar xzf apache-maven-3.3.9-bin.tar.gz
RUN mkdir /usr/local/maven
RUN mv apache-maven-3.3.9/ /usr/local/maven/
RUN alternatives --install /usr/bin/mvn mvn /usr/local/maven/apache-maven-3.3.9/bin/mvn 1
RUN gu install native-image
```

I needed to install native-image and increase the heap size 30gb might be overkill but it was failing with everything up until 10 gb and I got tired of smaller increments.

**Comment by sstubbs** [comment]
I've added the --no-server to the buildargs to resolve the large amount of memory being used. It also builds quicker.

**Comment by sstubbs** [comment]
For some reason it's just slow in docker compared to locally installed graal. Build time in docker even with a different dockerfile using debian and manually installing graal takes 6 minutes compared to 1 minute locally. I also don't have memory issues locally. By locally I'm using WSL so not completely native linux.

First project I've ported over is down from 150mb ram usage to 10mb. I honestly can't believe it. The GC also frees up ram back to the os like shenandoah which I previously had to use. This is amazing! Thank you very very much!

**Comment by pmlopes** [comment]
Perhaps you should ask on the graalvm project as the build itself is not related to vertx and I can't tell you what to do except stating what's on their docs and my own experiences...

**Comment by sstubbs** [comment]
OK will do.

**Comment by sstubbs** [comment]
Here is the issue for your reference https://github.com/oracle/graal/issues/1605

**Comment by sstubbs** [comment]
Thanks for updating this. It's working well for me. I've also moved over to linux from windows wsl and it gets built quickly in a container.
